################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
bsp \
cmsis \
firmware \
include/middlewares/3rd_party/lvgl/demos/benchmark/assets \
include/middlewares/3rd_party/lvgl/demos/benchmark \
include/middlewares/3rd_party/lvgl/demos/keypad_encoder \
include/middlewares/3rd_party/lvgl/demos/music/assets \
include/middlewares/3rd_party/lvgl/demos/music \
include/middlewares/3rd_party/lvgl/demos/stress \
include/middlewares/3rd_party/lvgl/demos/widgets/assets \
include/middlewares/3rd_party/lvgl/demos/widgets \
include/middlewares/3rd_party/lvgl/env_support/rt-thread \
include/middlewares/3rd_party/lvgl/env_support/rt-thread/squareline \
include/middlewares/3rd_party/lvgl/examples/anim \
include/middlewares/3rd_party/lvgl/examples/assets \
include/middlewares/3rd_party/lvgl/examples/assets/emoji \
include/middlewares/3rd_party/lvgl/examples/event \
include/middlewares/3rd_party/lvgl/examples/get_started \
include/middlewares/3rd_party/lvgl/examples/layouts/flex \
include/middlewares/3rd_party/lvgl/examples/layouts/grid \
include/middlewares/3rd_party/lvgl/examples/libs/bmp \
include/middlewares/3rd_party/lvgl/examples/libs/ffmpeg \
include/middlewares/3rd_party/lvgl/examples/libs/freetype \
include/middlewares/3rd_party/lvgl/examples/libs/gif \
include/middlewares/3rd_party/lvgl/examples/libs/png \
include/middlewares/3rd_party/lvgl/examples/libs/qrcode \
include/middlewares/3rd_party/lvgl/examples/libs/rlottie \
include/middlewares/3rd_party/lvgl/examples/libs/sjpg \
include/middlewares/3rd_party/lvgl/examples/others/fragment \
include/middlewares/3rd_party/lvgl/examples/others/gridnav \
include/middlewares/3rd_party/lvgl/examples/others/ime \
include/middlewares/3rd_party/lvgl/examples/others/imgfont \
include/middlewares/3rd_party/lvgl/examples/others/monkey \
include/middlewares/3rd_party/lvgl/examples/others/msg \
include/middlewares/3rd_party/lvgl/examples/others/snapshot \
include/middlewares/3rd_party/lvgl/examples/porting \
include/middlewares/3rd_party/lvgl/examples/scroll \
include/middlewares/3rd_party/lvgl/examples/styles \
include/middlewares/3rd_party/lvgl/examples/widgets/animimg \
include/middlewares/3rd_party/lvgl/examples/widgets/arc \
include/middlewares/3rd_party/lvgl/examples/widgets/bar \
include/middlewares/3rd_party/lvgl/examples/widgets/btn \
include/middlewares/3rd_party/lvgl/examples/widgets/btnmatrix \
include/middlewares/3rd_party/lvgl/examples/widgets/calendar \
include/middlewares/3rd_party/lvgl/examples/widgets/canvas \
include/middlewares/3rd_party/lvgl/examples/widgets/chart \
include/middlewares/3rd_party/lvgl/examples/widgets/checkbox \
include/middlewares/3rd_party/lvgl/examples/widgets/colorwheel \
include/middlewares/3rd_party/lvgl/examples/widgets/dropdown \
include/middlewares/3rd_party/lvgl/examples/widgets/img \
include/middlewares/3rd_party/lvgl/examples/widgets/imgbtn \
include/middlewares/3rd_party/lvgl/examples/widgets/keyboard \
include/middlewares/3rd_party/lvgl/examples/widgets/label \
include/middlewares/3rd_party/lvgl/examples/widgets/led \
include/middlewares/3rd_party/lvgl/examples/widgets/line \
include/middlewares/3rd_party/lvgl/examples/widgets/list \
include/middlewares/3rd_party/lvgl/examples/widgets/menu \
include/middlewares/3rd_party/lvgl/examples/widgets/meter \
include/middlewares/3rd_party/lvgl/examples/widgets/msgbox \
include/middlewares/3rd_party/lvgl/examples/widgets/obj \
include/middlewares/3rd_party/lvgl/examples/widgets/roller \
include/middlewares/3rd_party/lvgl/examples/widgets/slider \
include/middlewares/3rd_party/lvgl/examples/widgets/span \
include/middlewares/3rd_party/lvgl/examples/widgets/spinbox \
include/middlewares/3rd_party/lvgl/examples/widgets/spinner \
include/middlewares/3rd_party/lvgl/examples/widgets/switch \
include/middlewares/3rd_party/lvgl/examples/widgets/table \
include/middlewares/3rd_party/lvgl/examples/widgets/tabview \
include/middlewares/3rd_party/lvgl/examples/widgets/textarea \
include/middlewares/3rd_party/lvgl/examples/widgets/tileview \
include/middlewares/3rd_party/lvgl/examples/widgets/win \
include/middlewares/3rd_party/lvgl/src/core \
include/middlewares/3rd_party/lvgl/src/draw/arm2d \
include/middlewares/3rd_party/lvgl/src/draw \
include/middlewares/3rd_party/lvgl/src/draw/nxp/pxp \
include/middlewares/3rd_party/lvgl/src/draw/nxp/vglite \
include/middlewares/3rd_party/lvgl/src/draw/sdl \
include/middlewares/3rd_party/lvgl/src/draw/stm32_dma2d \
include/middlewares/3rd_party/lvgl/src/draw/sw \
include/middlewares/3rd_party/lvgl/src/draw/swm341_dma2d \
include/middlewares/3rd_party/lvgl/src/extra/layouts/flex \
include/middlewares/3rd_party/lvgl/src/extra/layouts/grid \
include/middlewares/3rd_party/lvgl/src/extra/libs/bmp \
include/middlewares/3rd_party/lvgl/src/extra/libs/ffmpeg \
include/middlewares/3rd_party/lvgl/src/extra/libs/freetype \
include/middlewares/3rd_party/lvgl/src/extra/libs/fsdrv \
include/middlewares/3rd_party/lvgl/src/extra/libs/gif \
include/middlewares/3rd_party/lvgl/src/extra/libs/png \
include/middlewares/3rd_party/lvgl/src/extra/libs/qrcode \
include/middlewares/3rd_party/lvgl/src/extra/libs/rlottie \
include/middlewares/3rd_party/lvgl/src/extra/libs/sjpg \
include/middlewares/3rd_party/lvgl/src/extra \
include/middlewares/3rd_party/lvgl/src/extra/others/fragment \
include/middlewares/3rd_party/lvgl/src/extra/others/gridnav \
include/middlewares/3rd_party/lvgl/src/extra/others/ime \
include/middlewares/3rd_party/lvgl/src/extra/others/imgfont \
include/middlewares/3rd_party/lvgl/src/extra/others/monkey \
include/middlewares/3rd_party/lvgl/src/extra/others/msg \
include/middlewares/3rd_party/lvgl/src/extra/others/snapshot \
include/middlewares/3rd_party/lvgl/src/extra/themes/basic \
include/middlewares/3rd_party/lvgl/src/extra/themes/default \
include/middlewares/3rd_party/lvgl/src/extra/themes/mono \
include/middlewares/3rd_party/lvgl/src/extra/widgets/animimg \
include/middlewares/3rd_party/lvgl/src/extra/widgets/calendar \
include/middlewares/3rd_party/lvgl/src/extra/widgets/chart \
include/middlewares/3rd_party/lvgl/src/extra/widgets/colorwheel \
include/middlewares/3rd_party/lvgl/src/extra/widgets/imgbtn \
include/middlewares/3rd_party/lvgl/src/extra/widgets/keyboard \
include/middlewares/3rd_party/lvgl/src/extra/widgets/led \
include/middlewares/3rd_party/lvgl/src/extra/widgets/list \
include/middlewares/3rd_party/lvgl/src/extra/widgets/menu \
include/middlewares/3rd_party/lvgl/src/extra/widgets/meter \
include/middlewares/3rd_party/lvgl/src/extra/widgets/msgbox \
include/middlewares/3rd_party/lvgl/src/extra/widgets/span \
include/middlewares/3rd_party/lvgl/src/extra/widgets/spinbox \
include/middlewares/3rd_party/lvgl/src/extra/widgets/spinner \
include/middlewares/3rd_party/lvgl/src/extra/widgets/tabview \
include/middlewares/3rd_party/lvgl/src/extra/widgets/tileview \
include/middlewares/3rd_party/lvgl/src/extra/widgets/win \
include/middlewares/3rd_party/lvgl/src/font \
include/middlewares/3rd_party/lvgl/src/hal \
include/middlewares/3rd_party/lvgl/src/misc \
include/middlewares/3rd_party/lvgl/src/widgets \
include/middlewares/3rd_party/lvgl/tests/makefile \
include/middlewares/3rd_party/lvgl/tests/src \
include/middlewares/3rd_party/lvgl/tests/src/test_cases \
include/middlewares/3rd_party/lvgl/tests/src/test_fonts \
include/middlewares/3rd_party/lvgl/tests/unity \
include/middlewares/i2c_application_library \
user \
user/hardware/lcd \
user/hardware/spi \
user/hardware/touch \

